services:
  db:
    image: postgres:15-alpine
    container_name: ymislucas-db-dev
    restart: always
    environment:
      POSTGRES_USER: lucas_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ymislucas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: